---
image: maven:3-jdk-8
cache:
    paths:
        - $HOME/.m2/
variables:
    MAVEN_CLI_OPTS: "-s /.m2/settings.xml -B"
    SONAR_PROJECT_NAME: "project-demo"
stages:
    - build

maven:build:
    stage: build
    environment: staging
    script:
        - "mvn $MAVEN_CLI_OPTS clean compile"
    artifacts:
    when: on_success
    paths:
        - target/